FROM node:14 as base

FROM base as builder
WORKDIR /build
COPY /src ./src
COPY /public ./public
COPY package*.json ./
RUN npm install
RUN npm run build

FROM base as development
WORKDIR /usr/src/app
COPY --from=builder /build/node_modules ./node_modules

FROM nginx
WORKDIR /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /build/node_modules ./node_modules
COPY --from=builder /build/dist .

