version: "3.9"
services:
  crystalsfrontend:
    container_name: crystalsfrontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - crystalsbackend
    ports:
      - 80:80
  crystalsbackend:
    container_name: crystalsbackend
    build:
      context: .
      target: production
      dockerfile: Dockerfile.backend
    depends_on:
      - crystalsdb
    environment:
      DB_HOST: crystalsdb
      DB_USERNAME: postgres
      DB_PASSWORD: pi
    command: bash -c "npx wait-port crystalsdb:5432; npx sequelize-cli db:migrate; node server.js"
  crystalsdb:
    container_name: crystalsdb
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pi
      POSTGRES_DB: crystal_index_db
    volumes:
      - ./data:/var/lib/postgresql/data     
 
