version: "3.9"
services:
  crystalsfrontend:
    container_name: crystalsfrontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:8080"
  crystalsbackend:
    container_name: crystalsbackend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: crystalsdb
      DB_USERNAME: postgres
      DB_PASSWORD: pi
    command: bash -c "npx wait-port crystalsdb:5432; npx sequelize-cli db:migrate; node server.js"
  crystalsdb:
    container_name: crystalsdb
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pi
      POSTGRES_DB: crystal_index_dev
