version: "3.9"
services:
  crystalsfrontend:
    container_name: crystalsfrontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:8080"
  crystalsbackend:
    container_name: crystalsbackend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
  crystalsdb:
    container_name: crystalsdb
    image: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: crystal_index_dev
          
        # environment:
        #   DB_HOST: crystalsdb
        #   DB_USERNAME: hellosammii
        #   DB_PASSWORD: hellocrystals