# fly.toml file generated for crystal-index on 2023-06-02T11:09:35+01:00

app = "crystal-index"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  # [[statics]]
  #   url_prefix = "/public"
  #   guest_path = "/app/public"
